version: '3.4'

volumes:
    data-volume:
    admin-vendor:
    admin-cache:
    www-vendor:
    www-cache:

networks:
    tagwalk-local:
        external:
            name: tagwalk

services:
    db:
        image: mariadb:10.0
        command: --max_allowed_packet=128M
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - data-volume:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d/
        ports:
            - 3306:3306
        networks:
            - tagwalk-local
    php:
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        environment:
            COMPOSER_ALLOW_SUPERUSER: 1
            COMPOSER_MEMORY_LIMIT: -1
        volumes:
            - ${BACK_APP_PATH}:/var/www/tagwalk-admin
            - admin-vendor:/var/www/tagwalk-admin/vendor
            - admin-cache:/var/www/tagwalk-admin/app/cache
            - ${FRONT_APP_PATH}:/var/www/tagwalk-www
            - www-vendor:/var/www/tagwalk-www/vendor
            - www-cache:/var/www/tagwalk-www/app/cache
            - ./logs/symfony/admin:/var/www/tagwalk-admin/app/logs:delegated
            - ./logs/symfony/www:/var/www/tagwalk-www/app/logs:delegated
            - ./php7-fpm/php.ini:/usr/local/etc/php/conf.d/custom.ini:cached
            - ../uploads:/var/www/tagwalk-admin/uploads:cached
        ports:
            - 9000
        networks:
            - tagwalk-local
    nginx:
        build: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ${BACK_APP_PATH}/web:/var/www/tagwalk-admin/web:cached
            - ${FRONT_APP_PATH}/web:/var/www/tagwalk-www/web:cached
            - ../uploads:/var/www/tagwalk-admin/uploads:cached
            - ./logs/nginx/:/var/log/nginx:delegated
            - ./nginx/certs:/etc/nginx/ssl:cached
        depends_on: [ php ]
        networks:
            - tagwalk-local
    ftpd:
        build: proftpd
        ports:
            - 20:20
            - 21:21
        volumes:
          - ../uploads:/home/ftp/uploads
        privileged: true
        networks:
            - tagwalk-local
